"""Add subscription.

Revision ID: a17d9457c609
Revises: cf99892870ef
Create Date: 2021-06-16 17:34:13.699040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17d9457c609'
down_revision = 'cf99892870ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed')
    # ### end Alembic commands ###
